### ISSUE TITLE
uploader.py error line 25

### ISSUE THREAD

**Issue by luchoLoky** [546200350/TikTokUploder#17]
tempInfo = r.json()['project']
KeyError: 'project'

**Comment by 546200350** [comment]
maybe you can debugge this line and find the response.
try to repalce request domain  us->www

**Comment by luchoLoky** [comment]
thanks! fixed with www

**Comment by Zgj2005** [comment]
Traceback (most recent call last):
  File "uploader.py", line 114, in <module>
    uploadVideo(args.session_id, args.path, args.title, args.tags, args.users)
  File "uploader.py", line 25, in uploadVideo
    tempInfo = r.json()['project']
KeyError: 'project'

**Comment by Zgj2005** [comment]
Is there any way to resolve this error by replacing the US with WWW? Thank you

**Comment by bilalazza** [comment]
me too i have replaced all of us with www and still get this error can anyone help me please?

**Comment by Zgj2005** [comment]
Finally, this problem has been solved. The session ID must be accurately found and a VPN is required
